Vagrant.configure(2) do |config|
  config.vm.define "pandorasbox" do |pandorasbox|

    # This tell vagrant what OS to use
    # We are using Trusty Ubuntu, which is a flavor of Linux.
    pandorasbox.vm.box = "ubuntu/bionic64"
    
    # This tells vagrant what to call the new machine
    pandorasbox.vm.hostname = "pandorasbox"

    # This is the hardware configuration
    # We will loosely imitate an Amazon EC2 T2 Micro server
    pandorasbox.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    # Network configuration
    pandorasbox.vm.network "private_network", type: "dhcp"
    pandorasbox.vm.network "forwarded_port", guest: 22, host: 2222

    # This is the directory that will house all of our personal items.
    # Everything in this current directory will be put here!
    pandorasbox.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777", "fmode=777"]

    pandorasbox.vm.post_up_message = nil

    # Tell vagrant where to find provisioning procedures
    pandorasbox.vm.provision "shell" do |pr|
      pr.path = "./provision/provision.sh"
      pr.env = {}
      pr.privileged = false
    end
  end
end
